language: java

jdk:
  - openjdk7
  - oraclejdk7

branches:
  only:
    - master
    - stage

install: "mvn -DskipTests=true install"

before_script: "cp src/main/resources/sample-settings.xml ${HOME}/.m2/settings.xml"

script:
  - sudo ln -s `pwd` /opt/freelib-djatoka
  - sudo etc/init.d/djatoka start
  - sudo mvn -Ptravis install

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: change
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
