language: java

jdk:
  - openjdk7
  - oraclejdk7

branches:
  only:
    - fedora

install: "mvn -DskipTests=true install && ls -Ra && ls -a ~"

before_script: "cp src/main/resources/sample-settings.xml ~/.m2/settings.xml && mvn jetty:run-forked"

script: "mvn -Ptravis install"

notifications:
  email:
    recipients:
      - ksclarke@gmail.com
    on_failure: never
    on_success: change
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
